<?php
/**********************************************************************
    Copyright (C) Simplex, Bluechip Technologies Ltd
***********************************************************************/
/*
	This file contains templates for all country specific functions.
	If your locale needs special functionality provided by hook functions
	copy this file to respective lang/xx_XX directory and edit templates below.
	You can safely remove not used function templates.
*/
?>