<?php
/**********************************************************************
    Copyright (C) Simplex, Bluechip Technologies Ltd
***********************************************************************/
include_once($path_to_root . "/includes/date_functions.inc");

include_once($path_to_root . "/includes/ui.inc");

include_once($path_to_root . "/purchasing/includes/ui/invoice_ui.inc");
include_once($path_to_root . "/simplex/purchasing/includes/ui/pr_ui.inc");
include_once($path_to_root . "/purchasing/includes/ui/grn_ui.inc");
//--------------------------------------------------------------------------------------
?>